<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Replication paper</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="JaclynM_Replication_AN588_files/libs/clipboard/clipboard.min.js"></script>
<script src="JaclynM_Replication_AN588_files/libs/quarto-html/quarto.js"></script>
<script src="JaclynM_Replication_AN588_files/libs/quarto-html/popper.min.js"></script>
<script src="JaclynM_Replication_AN588_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="JaclynM_Replication_AN588_files/libs/quarto-html/anchor.min.js"></script>
<link href="JaclynM_Replication_AN588_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="JaclynM_Replication_AN588_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="JaclynM_Replication_AN588_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="JaclynM_Replication_AN588_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="JaclynM_Replication_AN588_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication paper</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="paper-introduction" class="level2">
<h2 class="anchored" data-anchor-id="paper-introduction">Paper Introduction</h2>
<p>The paper I am focusing on is Attractiveness of female sexual signaling predicts differences in female grouping patterns between bonobos and chimpanzees by Martin Surbeck <em>et al.</em> (2021). The original paper investigates <strong>how female sexual signaling influences social grouping patterns in bonobos and chimpanzees</strong>. It aims to determine whether differences in female-female associations between the two species are driven primarily by ecological factors or by sexual signaling.</p>
<p><strong>Data Set Used</strong>: The study relies on observational data from three wild communities—one bonobo (Bompusa) and two chimpanzee (Taï East and Taï South) populations between February 2015 and December 2017. Researchers collected focal follow data on female party size, time spent alone, presence of maximally tumescent females, and food availability indicators.</p>
<p><strong>Analyses Conducted</strong>:</p>
<ul>
<li><p>Comparison of female party sizes across species and communities.</p></li>
<li><p>Assessment of time females spend alone.</p></li>
<li><p>Statistical models examining the effect of maximally tumescent females on female grouping behavior, controlling for food availability.</p></li>
<li><p>Evaluation of the relative influence of ecological and sexual signaling factors on female sociality.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<p>Data was in an Excel file so I need to get the file into R using the package “readxl”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"/Users/jaclynmeyer/Downloads/rawdata_female_gregariousness (1).xls"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 409 × 13
   `Focal ID` Species Community  Date i.halfday `Number female party members`
        &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;                             &lt;dbl&gt;
 1         15 bonobo  LK_West   42064 to_check                          4.43 
 2         28 bonobo  LK_West   42065 morning                           0.889
 3         34 bonobo  LK_West   42068 afternoon                         1.11 
 4         13 bonobo  LK_West   42069 morning                           5    
 5         28 bonobo  LK_West   42072 morning                           9.8  
 6         15 bonobo  LK_West   42073 afternoon                         3.43 
 7         25 bonobo  LK_West   42074 morning                           1    
 8          4 bonobo  LK_West   42075 morning                           3    
 9         15 bonobo  LK_West   42078 morning                           3    
10          7 bonobo  LK_West   42081 morning                           1    
# ℹ 399 more rows
# ℹ 7 more variables: `Number oservations` &lt;dbl&gt;, `Number MTF cathegory` &lt;dbl&gt;,
#   `Percentage MTF precent in party` &lt;dbl&gt;, `Percentage only females` &lt;dbl&gt;,
#   `Percentage alone` &lt;dbl&gt;, `Percentage Samesex` &lt;dbl&gt;,
#   `Proportion feeding time monthly` &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Focal_ID"</span>, <span class="st">"Species"</span>, <span class="st">"Community"</span>, <span class="st">"Date"</span>, <span class="st">"i_halfday"</span>, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Number_female_party_members"</span>, <span class="st">"Number_observations"</span>, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Number_MTF_category"</span>, <span class="st">"Percentage_MTF_present_in_party"</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Percentage_only_females"</span>, <span class="st">"Percentage_alone"</span>, </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Percentage_Samesex"</span>, <span class="st">"Proportion_feeding_time_monthly"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Focal_ID <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>Focal_ID)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Species <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>Species)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Community <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>Community)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(data<span class="sc">$</span>Date, <span class="at">format=</span><span class="st">"%Y-%m-%d"</span>) <span class="co"># Adjust format as needed</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>i_halfday <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>i_halfday)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Number_MTF_category <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>Number_MTF_category) <span class="co"># Convert to factor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="descriptive-analysis" class="level1">
<h1>Descriptive Analysis</h1>
<section id="analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="analysis-1">Analysis 1</h2>
<section id="female-grouping-patterns-summarizing-time-females-spent-in-parties-alone-or-in-female-only-associations" class="level3">
<h3 class="anchored" data-anchor-id="female-grouping-patterns-summarizing-time-females-spent-in-parties-alone-or-in-female-only-associations">Female Grouping Patterns: Summarizing time females spent in parties, alone, or in female-only associations</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean female party size by community</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>party_size_summary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_female_party_size =</span> <span class="fu">mean</span>(Number_female_party_members, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_female_party_size =</span> <span class="fu">sd</span>(Number_female_party_members, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">se_female_party_size =</span> sd_female_party_size <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(party_size_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  Community mean_female_party_size sd_female_party_size     n
  &lt;fct&gt;                      &lt;dbl&gt;                &lt;dbl&gt; &lt;int&gt;
1 LK_West                     4.51                 3.13   175
2 Tai_East                    3.32                 2.03   110
3 Tai_South                   3.75                 2.14   124
# ℹ 1 more variable: se_female_party_size &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The results from the paper say “While there was only a trend for statistical differences between bonobo females and chimpanzee females from Taï South (4.5 vs.&nbsp;3.7, p = 0.097, Fig. 1), female bonobos had more females in their party than chimpanzee females in Taï East (4.5 vs.&nbsp;3.3, p = 0.01, Fig. 1).”. Here in the replication we can see the same results with the bonobos having a mean female population of 4.5 while the Tai East Chimps have a mean female population of 3.3 and the Tai South Chimps have a mean female population of 3.7.</p>
</section>
<section id="presence-of-maximally-tumescent-females-mtf" class="level3">
<h3 class="anchored" data-anchor-id="presence-of-maximally-tumescent-females-mtf">Presence of Maximally Tumescent Females (MTF)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of observation days with MTFs present</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mtf_presence_by_community <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community, Date) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">has_mtf =</span> <span class="fu">any</span>(Percentage_MTF_present_in_party <span class="sc">&gt;</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_days =</span> <span class="fu">n</span>(),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">days_with_mtf =</span> <span class="fu">sum</span>(has_mtf),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage_days_with_mtf =</span> days_with_mtf <span class="sc">/</span> total_days <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Community'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print percentage of days with MTF</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mtf_presence_by_community)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Community total_days days_with_mtf percentage_days_with_mtf
  &lt;fct&gt;          &lt;int&gt;         &lt;int&gt;                    &lt;dbl&gt;
1 LK_West          163            57                     35.0
2 Tai_East          79            23                     29.1
3 Tai_South         85            19                     22.4</code></pre>
</div>
</div>
<p>The results in the paper state “Overall, MTFs were present on more days in bonobos as compared to chimpanzees (38% of observation days versus 34% <sub>Taï&nbsp;East</sub> and 23% <sub>Taï&nbsp;South</sub>)” This is different from the results seen here. I thought maybe the researchers were counting each focal follow separately rather than aggregating by calendar date, so I tried to recreated the results from the paper using focal ID rather than date</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of focal follows with MTFs present</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mtf_presence_by_community <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Assuming you have a column identifying each unique focal follow</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community, Focal_ID) <span class="sc">%&gt;%</span>  </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">has_mtf =</span> <span class="fu">any</span>(Percentage_MTF_present_in_party <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_follows =</span> <span class="fu">n</span>(),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">follows_with_mtf =</span> <span class="fu">sum</span>(has_mtf),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage_follows_with_mtf =</span> follows_with_mtf <span class="sc">/</span> total_follows <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print percentage of focal follows with MTF</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mtf_presence_by_community)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Community total_follows follows_with_mtf percentage_follows_with_mtf
  &lt;fct&gt;             &lt;int&gt;            &lt;int&gt;                       &lt;dbl&gt;
1 LK_West              13               13                         100
2 Tai_East              8                8                         100
3 Tai_South            13               13                         100</code></pre>
</div>
</div>
<p>This clearly did not work as we are now getting 100% for all communities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check number of focal follows per community</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_follows =</span> <span class="fu">n_distinct</span>(Focal_ID))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  Community n_follows
  &lt;fct&gt;         &lt;int&gt;
1 LK_West          13
2 Tai_East          8
3 Tai_South        13</code></pre>
</div>
</div>
<p>So let’s see if we can determine how the observes are getting their results. First I’m going to check the distribution of MTF presence values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the distribution of MTF presence values</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_mtf =</span> <span class="fu">min</span>(Percentage_MTF_present_in_party),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_mtf =</span> <span class="fu">mean</span>(Percentage_MTF_present_in_party),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_mtf =</span> <span class="fu">max</span>(Percentage_MTF_present_in_party),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">zero_mtf =</span> <span class="fu">sum</span>(Percentage_MTF_present_in_party <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_rows =</span> <span class="fu">n</span>()</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  Community min_mtf mean_mtf max_mtf zero_mtf total_rows
  &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;int&gt;      &lt;int&gt;
1 LK_West         0    0.309       1      114        175
2 Tai_East        0    0.199       1       80        110
3 Tai_South       0    0.116       1       99        124</code></pre>
</div>
</div>
<p>So this seems in line with other results from the paper. Let’s see if we calculate the percentage of unique days with MTFs present give us the same results as the paper.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of unique days with MTFs present</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>mtf_presence_by_day <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Assuming you have a Date column</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Community, Date, Percentage_MTF_present_in_party) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get unique combination of community and date</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(Community, Date, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Group by community and date</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community, Date) <span class="sc">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">has_mtf =</span> <span class="fu">max</span>(Percentage_MTF_present_in_party) <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate percentages by community</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_days =</span> <span class="fu">n</span>(),</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">days_with_mtf =</span> <span class="fu">sum</span>(has_mtf),</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage_days_with_mtf =</span> days_with_mtf <span class="sc">/</span> total_days <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mtf_presence_by_day)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Community total_days days_with_mtf percentage_days_with_mtf
  &lt;fct&gt;          &lt;int&gt;         &lt;int&gt;                    &lt;dbl&gt;
1 LK_West          163            56                     34.4
2 Tai_East          79            19                     24.1
3 Tai_South         85            17                     20  </code></pre>
</div>
</div>
<p>These results are still off. So let’s see if they’re looking at all focal follows by each date.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative approach: Look at all focal follows by date</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>mtf_presence_by_day_alt <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Group by community and date</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community, Date) <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Check if any focal follow on that day had an MTF present</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">has_mtf =</span> <span class="fu">any</span>(Percentage_MTF_present_in_party <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate percentages by community</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_days =</span> <span class="fu">n</span>(),</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">days_with_mtf =</span> <span class="fu">sum</span>(has_mtf),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage_days_with_mtf =</span> days_with_mtf <span class="sc">/</span> total_days <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mtf_presence_by_day_alt) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Community total_days days_with_mtf percentage_days_with_mtf
  &lt;fct&gt;          &lt;int&gt;         &lt;int&gt;                    &lt;dbl&gt;
1 LK_West          163            57                     35.0
2 Tai_East          79            23                     29.1
3 Tai_South         85            19                     22.4</code></pre>
</div>
</div>
<p>While this is getting closer, it is still not giving us the same results as the paper. There are a few things that could be going on:</p>
<p><strong>Definition of “observation days”</strong>: The paper may be using a different definition of what constitutes an observation day - perhaps including only days with sufficient observation time or certain conditions.</p>
<p><strong>Calculation methodology</strong>: The authors might have used a different threshold or methodology to determine MTF presence on a given day.</p>
<p><strong>Data corrections</strong>: There might have been data corrections or updates after your dataset was compiled.</p>
<p>Though we could not get the exact percentages to be replicated we still see the same pattern the paper speaks about (bonobos &gt; Taï East &gt; Taï South).</p>
</section>
</section>
<section id="inferential-analysis" class="level2">
<h2 class="anchored" data-anchor-id="inferential-analysis">INFERENTIAL ANALYSIS</h2>
<section id="effect-of-mtf-presence-on-female-party-size" class="level3">
<h3 class="anchored" data-anchor-id="effect-of-mtf-presence-on-female-party-size">Effect of MTF Presence on Female Party Size</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data: Create categorical MTF variable similar to the paper</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (0, ≤1 excluding 0, &gt;1)</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MTF_cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    Percentage_MTF_present_in_party <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"0"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    Percentage_MTF_present_in_party <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> Percentage_MTF_present_in_party <span class="sc">&lt;=</span> <span class="dv">50</span> <span class="sc">~</span> <span class="st">"≤1"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    Percentage_MTF_present_in_party <span class="sc">&gt;</span> <span class="dv">50</span> <span class="sc">~</span> <span class="st">"&gt;1"</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>MTF_cat <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>MTF_cat, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"≤1"</span>, <span class="st">"&gt;1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3a: MTF as categorical variable</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model_3a <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Number_female_party_members <span class="sc">~</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                  Community <span class="sc">*</span> MTF_cat <span class="sc">+</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                  Proportion_feeding_time_monthly <span class="sc">+</span> </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                  (<span class="dv">1</span><span class="sc">|</span>Focal_ID), </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> data)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print model summary</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_3a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: 
Number_female_party_members ~ Community * MTF_cat + Proportion_feeding_time_monthly +  
    (1 | Focal_ID)
   Data: data

REML criterion at convergence: 1831

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.1652 -0.6850 -0.0600  0.5401  3.5200 

Random effects:
 Groups   Name        Variance Std.Dev.
 Focal_ID (Intercept) 0.2102   0.4584  
 Residual             5.0680   2.2512  
Number of obs: 409, groups:  Focal_ID, 34

Fixed effects:
                                Estimate Std. Error t value
(Intercept)                      4.77898    0.58791   8.129
CommunityTai_East               -0.47778    0.40243  -1.187
CommunityTai_South               0.02198    0.37403   0.059
MTF_cat≤1                        3.39339    0.36536   9.288
Proportion_feeding_time_monthly -3.85322    1.34695  -2.861
CommunityTai_East:MTF_cat≤1     -2.50993    0.60591  -4.142
CommunityTai_South:MTF_cat≤1    -2.39624    0.62485  -3.835</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(rn, minlength = 11): abbreviate used with non-ASCII chars</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Correlation of Fixed Effects:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(rn, minlength = 6): abbreviate used with non-ASCII chars</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intr) CmmT_E CmmT_S MTF_≤1 Prp___ CT_E:M
CmmntyT_Est -0.465                                   
CmmntyT_Sth -0.511  0.464                            
MTF_cat≤1   -0.365  0.346  0.374                     
Prprtn_fd__ -0.908  0.228  0.258  0.171              
CT_E:MTF_≤1  0.148 -0.460 -0.205 -0.589 -0.024       
CT_S:MTF_≤1  0.166 -0.190 -0.436 -0.576 -0.048  0.343</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create null model (without MTF effects)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>null_model_3a <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Number_female_party_members <span class="sc">~</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                       Community <span class="sc">+</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                       Proportion_feeding_time_monthly <span class="sc">+</span> </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                       (<span class="dv">1</span><span class="sc">|</span>Focal_ID), </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> data)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Likelihood ratio test comparing full model to null model</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_3a, null_model_3a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: data
Models:
null_model_3a: Number_female_party_members ~ Community + Proportion_feeding_time_monthly + (1 | Focal_ID)
model_3a: Number_female_party_members ~ Community * MTF_cat + Proportion_feeding_time_monthly + (1 | Focal_ID)
              npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
null_model_3a    6 1927.6 1951.7 -957.79   1915.6                         
model_3a         9 1848.9 1885.0 -915.43   1830.9 84.719  3  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>My analysis confirms the paper’s main finding that “there was a stronger increase in the number of party females in bonobos in the presence of maximally tumescent females” (P &lt; 0.001). While my model shows no significant difference between communities when MTFs are absent (supporting their “no species differences” claim), it reveals a dramatically stronger effect in bonobos (+3.39) compared to both Taï communities (+0.88 for Taï East, +0.99 for Taï South). This roughly 3.9x difference with Taï East aligns with their finding that “the effect was over three times larger in bonobos than in Taï East chimpanzees,” though my results show a 3.4x difference with Taï South rather than their reported “eight times larger.” My analysis of 409 focal follows (175 bonobo, 110 Taï East, 124 Taï South) provides robust statistical support (χ² = 84.719, p &lt; 2.2e-16) for the paper’s conclusion that “the presence of maximally tumescent females had a different influence on female grouping patterns in the three communities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3b: MTF as percentage variable</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>model_3b <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Number_female_party_members <span class="sc">~</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                  Community <span class="sc">*</span> Percentage_MTF_present_in_party <span class="sc">+</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                  Proportion_feeding_time_monthly <span class="sc">+</span> </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                  (<span class="dv">1</span><span class="sc">|</span>Focal_ID), </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> data)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print model summary</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_3b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: 
Number_female_party_members ~ Community * Percentage_MTF_present_in_party +  
    Proportion_feeding_time_monthly + (1 | Focal_ID)
   Data: data

REML criterion at convergence: 1810.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.4112 -0.6848 -0.0913  0.5466  3.4371 

Random effects:
 Groups   Name        Variance Std.Dev.
 Focal_ID (Intercept) 0.1647   0.4058  
 Residual             4.8601   2.2046  
Number of obs: 409, groups:  Focal_ID, 34

Fixed effects:
                                                   Estimate Std. Error t value
(Intercept)                                         4.64803    0.56950   8.162
CommunityTai_East                                  -0.45330    0.37889  -1.196
CommunityTai_South                                  0.04971    0.35201   0.141
Percentage_MTF_present_in_party                     3.97153    0.38499  10.316
Proportion_feeding_time_monthly                    -3.61530    1.31705  -2.745
CommunityTai_East:Percentage_MTF_present_in_party  -2.59822    0.71240  -3.647
CommunityTai_South:Percentage_MTF_present_in_party -2.05681    0.85933  -2.394

Correlation of Fixed Effects:
            (Intr) CmmT_E CmmT_S P_MTF_ Prp___ CT_E:P
CmmntyT_Est -0.470                                   
CmmntyT_Sth -0.503  0.468                            
Prcn_MTF___ -0.351  0.343  0.369                     
Prprtn_fd__ -0.913  0.239  0.255  0.162              
CT_E:P_MTF_  0.126 -0.440 -0.182 -0.529 -0.018       
CT_S:P_MTF_  0.078 -0.133 -0.380 -0.434  0.014  0.236</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create null model for model 3b</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>null_model_3b <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Number_female_party_members <span class="sc">~</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                       Community <span class="sc">+</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                       Proportion_feeding_time_monthly <span class="sc">+</span> </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                       (<span class="dv">1</span><span class="sc">|</span>Focal_ID), </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> data)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Likelihood ratio test comparing full model to null model</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_3b, null_model_3b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: data
Models:
null_model_3b: Number_female_party_members ~ Community + Proportion_feeding_time_monthly + (1 | Focal_ID)
model_3b: Number_female_party_members ~ Community * Percentage_MTF_present_in_party + Proportion_feeding_time_monthly + (1 | Focal_ID)
              npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
null_model_3b    6 1927.6 1951.7 -957.79   1915.6                         
model_3b         9 1829.7 1865.8 -905.82   1811.7 103.94  3  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>My analysis using percentage of time with MTF present confirms the paper’s finding that “in bonobos, an increase in the percentage of time with maximally tumescent females in the party strongly increased the number of females in the party” (P &lt; 0.001). My model shows a significant positive effect of MTF presence in bonobos (+3.97 per unit increase in percentage, t=10.316), with significantly smaller effects in both Taï communities (Taï East: +1.37, Taï South: +1.91). These translate to approximately 2.9x larger effect in bonobos than Taï East and 2.1x larger than Taï South, partially supporting their conclusion that “the effect was over three times larger in bonobos than in Taï East chimpanzees and eight times larger than in Taï South chimpanzees.” The likelihood ratio test (χ² = 103.94, p &lt; 2.2e-16) strongly supports the paper’s statement that interactions between percentage MTF presence and community were “significant (df = 2, χ² = 17.24, P &lt; 0.001),” confirming that “the presence of maximally tumescent females had a different influence on female grouping patterns in the three communities.</p>
</section>
</section>
<section id="visual-aspect" class="level2">
<h2 class="anchored" data-anchor-id="visual-aspect">Visual Aspect</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, calculate the count of observations for each value</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>point_sizes <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community, Number_female_party_members) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the counts back to the original data</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>data_with_counts <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(point_sizes, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Community"</span>, <span class="st">"Number_female_party_members"</span>))</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create color mapping (assuming 'Bompusa' is another name for 'LK_West')</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>community_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"LK_West"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Tai_East"</span> <span class="ot">=</span> <span class="st">"orange"</span>, <span class="st">"Tai_South"</span> <span class="ot">=</span> <span class="st">"orange"</span>)</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>fig1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_with_counts, <span class="fu">aes</span>(<span class="at">x =</span> Community, <span class="at">y =</span> Number_female_party_members)) <span class="sc">+</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add jittered points with size based on count</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">size =</span> count, <span class="at">color =</span> Community, <span class="at">alpha =</span> <span class="fl">0.7</span>), <span class="at">width =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add boxplot</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add model prediction line</span></span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="st">"red"</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"crossbar"</span>, </span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>               <span class="at">width =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Set colors manually</span></span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(community_colors, <span class="st">"red"</span> <span class="ot">=</span> <span class="st">"red"</span>), </span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>                     <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Customize point size and transparency</span></span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>), <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_alpha</span>(<span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Customize theme</span></span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add labels</span></span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Fig. 1: Differences between the Bompusa bonobo community and the two Taï chimpanzee</span><span class="sc">\n</span><span class="st">communities in the total number of adult females in the party of female focal individuals"</span>,</span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Community"</span>,</span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average number of female party members"</span></span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Rename communities if needed (change LK_West to Bompusa)</span></span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"LK_West"</span> <span class="ot">=</span> <span class="st">"Bompusa"</span>, <span class="st">"Tai_East"</span> <span class="ot">=</span> <span class="st">"Tai_East"</span>, <span class="st">"Tai_South"</span> <span class="ot">=</span> <span class="st">"Tai_South"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fig1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="JaclynM_Replication_AN588_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&lt;img src=“42003_2021_2641_Fig1_HTML.png” width=“600px”/&gt;</p>
<p>This looks extremely similar to the visual in the paper, though mine does look more sparse.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>